#!url=https://raw.githubusercontent.com/CHNJohnHK/shadowrocket-rules/main/module/ad-block.module
#!name=❌ AD Block
#!desc=JohnHK's Module
# 仅供学习交流 🈲️商业用途
# 部分转自他人
# 建议开启 HTTPS 解密 教程 https://t.me/h5683577/3 *此频道与 JohnHK 无任何关系
[General]
force-http-engine-hosts = %APPEND% *.cp31.ott.cibntv.net

[Rule]
# Google
URL-REGEX,^https:\/\/www\.google\.com\.hk\/ads,REJECT
DOMAIN,ade.googlesyndication.com,REJECT
DOMAIN,googleads4.g.doubleclick.net,REJECT
DOMAIN,pagead2.googlesyndication.com,REJECT
DOMAIN,googleads.g.doubleclick.net,REJECT
# Baidu 可能误杀
DOMAIN,hpd.baidu.com,REJECT
DOMAIN,hm.baidu.com,REJECT
DOMAIN-SUFFIX,pos.baidu.com,REJECT
DOMAIN-SUFFIX,mobads.baidu.com,REJECT
DOMAIN-SUFFIX,eclick.baidu.com,REJECT
DOMAIN-SUFFIX,entry.baidu.com,REJECT
DOMAIN-SUFFIX,hmma.baidu.com,REJECT
DOMAIN-SUFFIX,mobads-logs.baidu.com,REJECT
DOMAIN-SUFFIX,mobads.baidu.com,REJECT
DOMAIN-SUFFIX,mtj.baidu.com,REJECT
DOMAIN-SUFFIX,nsclick.baidu.com,REJECT
DOMAIN-SUFFIX,static.tieba.baidu.com,REJECT
DOMAIN-SUFFIX,ucstat.baidu.com,REJECT
DOMAIN-SUFFIX,union.baidu.com,REJECT
DOMAIN-SUFFIX,imageplus.baidu.com,REJECT
DOMAIN-SUFFIX,t10.baidu.com,REJECT
DOMAIN-SUFFIX,t11.baidu.com,REJECT
DOMAIN-SUFFIX,t12.baidu.com,REJECT
# 腾讯 可能误杀
DOMAIN,adsmind.apdcdn.tc.qq.com,REJECT
DOMAIN,adsmind.tc.qq.com,REJECT
DOMAIN,adsmind.gdtimg.com,REJECT
DOMAIN,btrace.qq.com,REJECT
DOMAIN,pgdt.gtimg.cn,REJECT
DOMAIN,pgdt.gtimg.com,REJECT
DOMAIN,pgdt.ugdtimg.com,REJECT
DOMAIN,wa.gtimg.com,REJECT
DOMAIN,splashqqlive.gtimg.com,REJECT
DOMAIN,wxsnsdythumb.wxs.qq.com,REJECT
DOMAIN,wxsnsdy.wxs.qq.com,REJECT
DOMAIN,ios.bugly.qq.com,REJEC
DOMAIN,pingma.qq.com,REJECT
DOMAIN-SUFFIX,e.qq.com,REJECT
DOMAIN-SUFFIX,l.qq.com,REJECT
DOMAIN-SUFFIX,gdt.qq.com,REJECT
DOMAIN-SUFFIX,mi.gdt.qq.com,REJECT
DOMAIN-SUFFIX,jcollection.shuqireader.com,REJECT
DOMAIN-SUFFIX,stats.jpush.cn,REJECT
DOMAIN-SUFFIX,sdk.kaijiawan.com,REJECT
DOMAIN,sdk.e.qq.com,REJECT
#新浪（可能有多余项） by h2y
DOMAIN-SUFFIX,ad.sina.com.cn,REJECT
DOMAIN-SUFFIX,adm.leju.sina.com.cn,REJECT
DOMAIN-SUFFIX,atm.sina.com,REJECT
DOMAIN-SUFFIX,dcads.sina.com.cn,REJECT
DOMAIN-SUFFIX,sax.sina.cn,REJECT
DOMAIN-SUFFIX,sax.sina.com.cn,REJECT
DOMAIN-SUFFIX,tjs.sjs.sinajs.cn,REJECT
# weibo（可能有多余项） by h2y
DOMAIN-SUFFIX,c.biz.weibo.com,REJECT
DOMAIN-SUFFIX,game.weibo.com,REJECT
DOMAIN-SUFFIX,c.wcpt.biz.weibo.com,REJECT
DOMAIN-SUFFIX,s.alitui.weibo.com,REJECT
DOMAIN-SUFFIX,zc.biz.weibo.com,REJECT
DOMAIN-SUFFIX,zymo.mps.weibo.com,REJECT
DOMAIN-SUFFIX,game.weibo.cn,REJECT
DOMAIN-SUFFIX,m.game.weibo.cn,REJECT
DOMAIN-SUFFIX,promote.biz.weibo.cn,REJECT
DOMAIN-SUFFIX,adimg.mobile.sina.cn,REJECT
DOMAIN-SUFFIX,newspush.sinajs.cn,REJECT
DOMAIN-SUFFIX,sdkapp.mobile.sina.cn,REJECT
DOMAIN-SUFFIX,sdkclick.mobile.sina.cn,REJECT
DOMAIN-SUFFIX,trends.mobile.sina.cn,REJECT
DOMAIN-SUFFIX,wbapp.mobile.sina.cn,REJECT
DOMAIN-SUFFIX,wbclick.mobile.sina.cn,REJECT
DOMAIN-SUFFIX,wbpctips.mobile.sina.cn,REJECT
DOMAIN-SUFFIX,ota.pay.mobile.sina.cn,REJECT
DOMAIN-SUFFIX,pay.mobile.sina.cn,REJECT
# 腾讯视频
DOMAIN-SUFFIX,tetrack.qq.com,REJECT
DOMAIN-SUFFIX,tpns.tencent.com,REJECT
DOMAIN-SUFFIX,api.poll.video.qq.com,REJECT
DOMAIN-SUFFIX,static-res.qq.com,REJECT
DOMAIN-SUFFIX,stat.tpns.tencent.com,REJECT
DOMAIN,h.trace.qq.com,REJECT
# 爱奇艺
DOMAIN,cr-status.iqiyi.com,REJECT
DOMAIN,f74f7f7765f8a2f6.ngaa.net.cn,REJECT
DOMAIN,ef-dongfeng.tanx.com,REJECT
DOMAIN,iqiyim.adtrack.enlightent.cn,REJECT
DOMAIN,t7z.cupid.iqiyi.com,DIRECT
DOMAIN,paopao-monitor.iqiyi.com,REJECT
DOMAIN,puma-api.iqiyi.com,REJECT
DOMAIN-SUFFIX,gdt.qq.com,REJECT
DOMAIN-SUFFIX,upqzfile.com,REJECT
DOMAIN,mbdlog.iqiyi.com,REJECT
DOMAIN-SUFFIX,cupid.iqiyi.com,REJECT
DOMAIN,myg.qy.net,REJECT
DOMAIN,www.qchannel01.cn,REJECT
DOMAIN,iqiyi-mipdx.cn.miaozhen.com,REJECT
DOMAIN,show.ssports.com,REJECT
DOMAIN-SUFFIX,afdback.ppsimg.com,REJECT
# 京东开屏广告屏蔽
URL-REGEX,https?:\/\/api\.m\.jd\.com\/client\.action\?functionId=start$,REJECT-TINYGIF

# 优酷去片头广告 by Choler
URL-REGEX,^http:\/\/.*\.cp31\.ott\.cibntv\.net\/youku\/,REJECT-TINYGIF

# 高德地图
DOMAIN,optimus-ads.amap.com,REJECT

# 不知名
DOMAIN,ulogs.umengcloud.com,REJECT
DOMAIN,ulogs.umeng.com,REJECT
DOMAIN,open.e.kuaishou.com,REJECT
DOMAIN,api-access.pangolin-sdk-toutiao.com,REJECT
DOMAIN,sdk.open.talk.getui.net,REJECT
DOMAIN,sdk.open.talk.getui.com,REJECT
DOMAIN,errlog.umeng.com,REJECT
DOMAIN,tnc3-aliec2.snssdk.com,REJECT
DOMAIN,sf3-fe-tos.pglstatp-toutiao.com,REJECT
DOMAIN,qzs.gdtimg.com,REJECT
DOMAIN-SUFFIX,adacale.de,REJECT
DOMAIN,stats.g.doubleclick.net,REJECT
DOMAIN,app-measurement.com,REJECT
DOMAIN,bymh26.com,REJECT
# 广告联盟 by h2y
DOMAIN-SUFFIX,doubleclick.net,REJECT
DOMAIN-SUFFIX,zhihu-analytics.zhihu.com,REJECT
DOMAIN-SUFFIX,log.cmbchina.com,REJECT
DOMAIN-SUFFIX,api.segment.io,REJECT
DOMAIN-SUFFIX,api.instabug.com,REJECT
DOMAIN-SUFFIX,adlog.flurry.com,REJECT
DOMAIN-SUFFIX,ads.flurry.com,REJECT
DOMAIN-SUFFIX,sd.domob.cn,REJECT
DOMAIN-SUFFIX,adjust.com,REJECT
DOMAIN-SUFFIX,adjust.io,REJECT
DOMAIN-SUFFIX,beacon.tingyun.com,REJECT
DOMAIN-SUFFIX,cmcore.com,REJECT
DOMAIN-SUFFIX,coremetrics.com,REJECT
DOMAIN-SUFFIX,irs01.com,REJECT
DOMAIN-SUFFIX,madmini.com,REJECT
DOMAIN-SUFFIX,optimizelyapis.com,REJECT
DOMAIN-SUFFIX,sitemeter.com,REJECT
DOMAIN-SUFFIX,wrating.com,REJECT
DOMAIN-SUFFIX,99click.com,REJECT
DOMAIN-SUFFIX,acs86.com,REJECT
DOMAIN-SUFFIX,adchina.com,REJECT
DOMAIN-SUFFIX,adcome.cn,REJECT
DOMAIN-SUFFIX,adinfuse.com,REJECT
DOMAIN-SUFFIX,adsmogo.org,REJECT
DOMAIN-SUFFIX,aduu.cn,REJECT
DOMAIN-SUFFIX,advertising.com,REJECT
DOMAIN-SUFFIX,adview.cn,REJECT
DOMAIN-SUFFIX,adwhirl.com,REJECT
DOMAIN-SUFFIX,adwo.com,REJECT
DOMAIN-SUFFIX,adxmi.com,REJECT
DOMAIN-SUFFIX,adzerk.net,REJECT
DOMAIN-SUFFIX,allyes.com,REJECT
DOMAIN-SUFFIX,anquan.org,REJECT
DOMAIN-SUFFIX,appads.com,REJECT
DOMAIN-SUFFIX,applifier.com,REJECT
DOMAIN-SUFFIX,applovin.com,REJECT
DOMAIN-SUFFIX,chartboost.com,REJECT
DOMAIN-SUFFIX,clicktracks.com,REJECT
DOMAIN-SUFFIX,clickzs.com,REJECT
DOMAIN-SUFFIX,guohead.com,REJECT
DOMAIN-SUFFIX,guomob.com,REJECT
DOMAIN-SUFFIX,immob.cn,REJECT
DOMAIN-SUFFIX,inmobi.com,REJECT
DOMAIN-SUFFIX,intely.cn,REJECT
DOMAIN-SUFFIX,ipinyou.com,REJECT
DOMAIN-SUFFIX,localytics.com,REJECT
DOMAIN-SUFFIX,mediav.com,REJECT
DOMAIN-SUFFIX,mobclix.com,REJECT
DOMAIN-SUFFIX,optaim.com,REJECT
DOMAIN-SUFFIX,quantserve.com,REJECT
DOMAIN-SUFFIX,responsys.net,REJECT
DOMAIN-SUFFIX,serving-sys.com,REJECT
DOMAIN-SUFFIX,smartmad.com,REJECT
DOMAIN-SUFFIX,smartadserver.com,REJECT
DOMAIN-SUFFIX,sponsorpay.com,REJECT
DOMAIN-SUFFIX,switchadhub.com,REJECT
DOMAIN-SUFFIX,thoughtleadr.com,REJECT
DOMAIN-SUFFIX,unimhk.com,Reject
DOMAIN-SUFFIX,unlitui.com,REJECT
DOMAIN-SUFFIX,uyunad.com,REJECT
DOMAIN-SUFFIX,vamaker.com,REJECT
DOMAIN-SUFFIX,waps.cn,REJECT
DOMAIN-SUFFIX,wiyun.com,REJECT
DOMAIN-SUFFIX,wooboo.com.cn,REJECT
DOMAIN-SUFFIX,wqmobile.com,REJECT
DOMAIN-SUFFIX,youmi.net,REJECT
DOMAIN-SUFFIX,zhiziyun.com,REJECT
DOMAIN-SUFFIX,segment.com,REJECT
DOMAIN-SUFFIX,taboola.com,REJECT
DOMAIN-SUFFIX,trc.taboola.com,REJECT
DOMAIN-SUFFIX,.inmobi.cn,REJECT
DOMAIN-SUFFIX,.criteo.com,REJECT

[URL Rewrite]
# 百度
^https?:\/\/fcvbjbcebos.baidu.com\/.+.mp4 - reject
^https?:\/\/cover.baidu.com\/cover\/page\/dspSwitchAds\/ - reject
^https?:\/\/baichuan.baidu.com\/rs\/adpmobile\/launch - reject
^https?:\/\/baichuan\.baidu\.com\/rs\/adpmobile\/launch - reject-img
^https?:\/\/api\d\.tuisong\.baidu\.com - reject-img
^https?:\/\/afd.baidu.com\/afd\/entry - reject
^https?:\/\/mobads\.baidu\.com\/cpro\/ui\/mads.+ - reject
(ps|sv|offnavi|newvector|ulog.imap|newloc)(.map)?.(baidu|n.shifen).com - reject
^https?+:\/\/issuecdn\.baidupcs\.com\/issue\/netdisk\/guanggao\/ - reject-200
^https?:\/\/[\s\S]*\.baidu\.com/.*?ad[xs]\.php - reject-img
^https?:\/\/afd\.baidu\.com\/afd\/entry - reject-img
^https?:\/\/als.baidu.com\/clog\/clog - reject
^https?:\/\/fcvbjbcebos\.baidu\.com\/.+?\.mp4 - reject-img
^https?:\/\/t\d{2}\.baidu\.com - reject-img
^https?:\/\/update\.pan\.baidu\.com\/statistics - reject
^https?:\/\/log.+?baidu\.com - reject
^https?:\/\/sa\d\.tuisong\.baidu\.com - reject-img
^https?:\/\/www.baidu.com\/?action=static&ms=1&version=css_page_2@0.*? - reject
# 百度网盘
^https?:\/\/pan\.baidu\.com\/rest\/\d\.\d\/pcs\/adx - reject
^https?:\/\/pan\.baidu\.com\/act\/api\/activityentry - reject
^https?:\/\/issuecdn\.baidupcs\.com\/issue\/netdisk\/guanggao - reject
^https?:\/\/update.pan.baidu.com\/statistics - reject
^https:\/\/pan\.baidu\.com\/pmall\/order\/privilege\/info - reject
^https:\/\/pan\.baidu\.com\/rest\/.+\/pcs\/adx - reject
^https:\/\/pan\.baidu\.com\/api\/useractivity\/activity - reject
^http:\/\/pan\.baidu\.com\/act\/.+\/bchannel\/list - reject
^https:\/\/pan\.baidu\.com\/api\/certuser\/get - reject
^https:\/\/ndstatic\.cdn\.bcebos\.com\/activity\/welfare\/js\/.+\.js - reject
^https:\/\/ndstatic\.cdn\.bcebos\.com\/activity\/welfare\/index\.html - reject
^https:\/\/staticsns\.cdn\.bcebos\.com\/amis\/.+/banner.png - reject
^http:\/\/rp\.hpplay\.cn\/logouts - reject
^https:\/\/pan\.baidu\.com\/component\/view\/(1510|1130)\?vip - reject


# 书旗小说去广告
^http:\/\/ut2\.shuqistat\.com\/.+\.gif - reject
^https?:\/\/sq\.sljkj\.com\/api\/sdk\/ads2 - reject
^https?:\/\/ocean\.shuqireader\.com\/api\/ad\/adserver\/.+ - reject
^https?:\/\/ocean\.shuqireader\.com\/api\/route\/iosReadPage\/ad.+ - reject
^https?:\/\/img-tailor\.11222\.cn\/pm\/app\/.+\.gif - reject
^https?:\/\/img-tailor\.11222\.cn\/cms\/upload\/img\/.+ - reject
^http:\/\/message\.shuqireader\.com\/message\/.+ - reject
^https?:\/\/mobads\.baidu\.com\/cpro\/ui\/mads.+ - reject
^http:\/\/101\.91\.69\.26:8080\/.+ - reject
^http:\/\/feedback.uc.cn\/feedback\/api\/get_unread_status - reject
^http:\/\/.+\.shuqireader\.com\/sapi\/.+ - reject

# 网易云广告 - m.ads.8le8le.com,iadmusicmat.music.com
^https?:\/\/iadmusicmat\.music\.126\.net\/.+\.jpg - reject
^http:\/\/interface\.music\.163\.com\/eapi\/ad\/config\/get - reject
^https?:\//m\.ads\.8le8le\.com\/adShow - reject

# 高德地图广告
^http:\/\/ems\.youku\.com\/imp\? - reject
^http:\/\/optimus-ads\.amap\.com\/uploadimg\/.+ - reject

# 腾讯视频广告屏蔽
^http:\/\/video\.dispatch\.tc\.qq\.com\/.+\.mp4 - reject
^http:\/\/.+\/vmind\.qqvideo\.tc\.qq\.com\/.+\.mp4 - reject
^http:\/\/wa\.gtimg\.com\/adxcdn\/.+\.jpg - reject
# 爱奇艺广告屏蔽
^http:\/\/.+\.iqiyipic\.com\/image\/.+\/ad\/.+\.jpg - reject
^http:\/\/static-s\.iqiyi\.com\/common\/.+\/Small_video/a2/af/.+\.png - reject
^http://msga/.cupid/.iqiyi/.com\/scp2\.gif - reject
https?:\/\/ssports\.iqiyi\.com\/app\/ - reject
https?:\/\/ssports\.iqiyi\.com\/json\/shop\/shopInfo  - reject
https?:\/\/.+\.iqiyi\.com\/videos\/other\/20$ - reject
https?:\/\/.+\.iqiyipic\.com\/image\/20*_100000 - reject
#https?:\/\/static\.iqiyi\.com\/js\/common\/.+\.js - reject
https?:\/\/t7z\.cupid\.iqiyi\.com\/show - reject
# 搬运爱奇艺 by gitee-木剑 - act.vip.iqiyi.com
^https?:\/\/iface\.iqiyi\.com\/api\/getNewAdInfo - reject
^https?:\/\/act\.vip\.iqiyi\.com\/interact\/api\/show\.do - reject
^https?:\/\/act\.vip\.iqiyi\.com\/interact\/api\/v\d\/show - reject
# 网易
^https?:\/\/p[^4](c)?\.music\.126\.net\/\w+==\/10995\d{13}\.jpg$ - reject-img
^https?:\/\/p\.c\.music\.126.net\/.*?jpg$ - reject
^https?:\/\/img1.126.net\/.+dpi=\w{7,8} - reject
^https?:\/\/img1.126.net\/channel14\/ - reject
^https?:\/\/iadmusicmat\.music.126.net\/.*?jpg$ - reject
^https?:\/\/p\d\.music\.126\.net\/\w+==\/\d+\.jpg$ - reject
^https?:\/\/www.icourse163.org\/.*?(Advertisement) - reject-img
^https?:\/\/nex.163.com\/q - reject
^https?:\/\/g1.163.com\/madfeedback - reject
^https?:\/\/client\.mail\.163\.com\/apptrack\/confinfo\/searchMultiAds - reject
^https?:\/\/c\.m\.163\.com\/nc\/gl\/ - reject
^https?+:\/\/www\.icourse163\.org\/mob\/j\/v1\/mobRecommendRPCBean\.getMaxWeightAdvertisement\.rpc - reject-200
^https?:\/\/interface3?\.music\.163\.com/eapi/(ad|abtest|sp|hot|store|mlog|search/(specialkeyword|defaultkeyword|hot)) - reject-img

# 网易邮箱 - appconf.mail.163.com,analytics.163.com
https:\/\/appconf\.mail\.163\.com\/mmad\/get\.do - reject
http:\/\/analytics\.163\.com\/ntes - reject
# 网易云音乐
^https?+:\/\/.+?\/eapi\/(?>ad|log)\/ - reject-200
^https?:\/\/interface(\d)?.music.163.com\/eapi\/ad\/ - reject
^https?:\/\/iadmusicmat\.music\.126\.net\/.+\.jpg - reject
^http:\/\/interface\.music\.163\.com\/eapi\/ad\/config\/get - reject
^https?:\//m\.ads\.8le8le\.com\/adShow - reject



# 搬运淘宝 by gitee-木剑 - gw.alicdn.com,heic.alicdn.com
^https?:\/\/(gw|heic)\.alicdn\.com\/\w{2}s\/.+\.jpg_(9\d{2}|\d{4}) - reject
^https?:\/\/(gw|heic)\.alicdn\.com\/imgextra\/.+\d{4}-\d{4}\.jpg_(9\d{2}|\d{4}) - reject
# 哔哩哔哩屏蔽广告浮窗
^https?:\/\/api\.bilibili\.com\/pgc\/activity\/deliver\/material\/receive - reject-dict
# 哔哩哔哩屏蔽IP请求
^https?:\/\/app\.bilibili\.com\/x\/resource\/ip - reject
# 哔哩哔哩屏蔽DefaultWord
^https?:\/\/app\.bilibili\.com\/bilibili\.app\.interface\.v1\.Search\/Default - reject
# 哔哩哔哩屏蔽首页右上活动[卸载重装]
^https?:\/\/app\.bilibili\.com\/x\/resource\/top\/activity - reject-dict
# 哔哩哔哩应用开屏去广告
^https://app.bilibili.com/x/v2/splash/show - reject-dict
# 哔哩哔哩Defaultword
^https://app.bilibili.com/x/v2/search/defaultwords - reject-dict
# 哔哩哔哩Material_Ad
^https?:\/\/api\.bilibili\.com\/x\/vip\/ads\/material\/report - reject-dict
# 哔哩哔哩小卡片广告
^https://api.bilibili.com/pgc/season/player/cards - reject-dict
# 哔哩哔哩去除动态中的话题
^https?:\/\/api\.vc\.bilibili\.com\/topic_svr\/v1\/topic_svr - reject-dict
# 哔哩哔哩漫画去广告
^https?:\/\/manga\.bilibili\.com\/twirp\/comic\.v\d\.Comic\/(Flash|ListFlash) - reject-dict
# bilibili - app.bilibili.com,manga.bilibili.com by deezertidal
^https?:\/\/app\.bilibili\.com\/x\/v\d\/splash\/ - reject
^https?:\/\/manga\.bilibili\.com\/twirp\/comic\.v\d\.Comic\/Flash - reject
# Google
^https?:\/\/.+\.googleapis.com/.+ad_break - reject-img
^https?:\/\/.+?\.googlevideo\.com\/ptracking\?pltype=adhost - reject-img
^https?:\/\/.+\.googleapis.com/.+log_event - reject-img
^https?:\/\/.+\.googleapis.com/adsmeasurement - reject-img
^https?:\/\/.+\.googlevideo\.com\/.+oad= - reject-img
^https?:\/\/.+\.googlevideo\.com\/ptracking - reject-img
^https?:\/\/pagead2\.googlesyndication\.com\/pagead\/ - reject-img
^https?:\/\/[\w-]+\.googlevideo\.com\/.+&(oad|ctier) - reject
^https?:\/\/.+\.googlevideo\.com\/videogoodput - reject-img
# CSDN
^https?:\/\/gw\.csdn\.net\/cms-app\/v\d+\/home_page\/open_advertisement - reject
# Spotify
^https?:\/\/spclient\.wg\.spotify\.com\/.+ad_slot - reject-img
^https?:\/\/spclient\.wg\.spotify\.com\/.+banners - reject-img
^https?:\/\/spclient\.wg\.spotify\.com\/.+crashlytics - reject-img
^https?:\/\/spclient\.wg\.spotify\.com\/.+doubleclick - reject-img
^https?:\/\/spclient\.wg\.spotify\.com\/.+enabled-tracks - reject-img
^https?:\/\/spclient\.wg\.spotify\.com\/.+event - reject-img
^https?:\/\/spclient\.wg\.spotify\.com\/.+promoted - reject-img
^https?:\/\/spclient\.wg\.spotify\.com\/.+sponsored - reject-img
^https?:\/\/spclient\.wg\.spotify\.com\/ad-logic - reject-img
^https?:\/\/spclient\.wg\.spotify\.com\/ads - reject-img
# 斗鱼
^https?:\/\/staticlive.douyucdn.cn\/.+\/getStartSend - reject
^https?:\/\/staticlive.douyucdn.cn\/upload\/signs\/ - reject
^https?:\/\/douyucdn.cn\/.+\/appapi\/getinfo - reject
^https?+:\/\/rtbapi\.douyucdn\.cn\/japi\/sign\/app\/getinfo - reject-200
^https?:\/\/capi.douyucdn.cn\/lapi\/sign\/app(api)?\/getinfo\?client_sys=ios - reject
^https?:\/\/capi\.douyucdn\.cn\/api\/ios_app\/check_update - reject-img
^https?:\/\/capi\.douyucdn\.cn\/api\/v1\/getStartSend?client_sys=ios - reject-img
^https?:\/\/douyucdn\.cn\/.+?\/appapi\/getinfo - reject-img
^https?:\/\/staticlive\.douyucdn\.cn\/.+?\/getStartSend - reject-img
^https?:\/\/staticlive\.douyucdn\.cn\/upload\/signs\/ - reject-img

[Script]
# 微信公众号 By Choler
微信公众号广告屏蔽 = type=http-response,pattern=^https?:\/\/mp\.weixin\.qq\.com\/mp\/getappmsgad,requires-body=1,script-path=https://raw.githubusercontent.com/NobyDa/Script/master/QuantumultX/File/Wechat.js
# weibo by yichahucha
http-response ^https?://(sdk|wb)app\.uve\.weibo\.com(/interface/sdk/sdkad.php|/wbapplua/wbpullad.lua) requires-body=1,script-path=https://raw.githubusercontent.com/yichahucha/surge/master/wb_launch.js
http-response ^https?://m?api\.weibo\.c(n|om)/2/(statuses/(unread|extend|positives/get|(friends|video)(/|_)(mix)?timeline)|stories/(video_stream|home_list)|(groups|fangle)/timeline|profile/statuses|comments/build_comments|photo/recommend_list|service/picfeed|searchall|cardlist|page|!/(photos/pic_recommend_status|live/media_homelist)|video/tiny_stream_video_list|photo/info|remind/unread_count) requires-body=1,max-size=-1,script-path=https://raw.githubusercontent.com/yichahucha/surge/master/wb_ad.js
# AdGuard by itcast-l
AdGuard 解锁永久高级版 = type=http-response,pattern=^https?:\/\/mobile-api\.adguard\.org\/api\/.+\/ios_validate_receipt,requires-body=1,max-size=0,script-path=https://github.com/itcast-l/shadowrocket-module/raw/main/js/Adguard.js
# 百度网盘解锁倍速 by Nobyda
http-response https:\/\/pan\.baidu\.com\/rest\/\d\.\d\/membership\/user script-path=https://raw.githubusercontent.com/chengkongyiban/shadowrocket/main/scripts/bdcloud.js,requires-body=true,script-update-interval=0,tag=BaiduCloud
# 哔哩哔哩Proto去广告
bilibili-proto = type=http-response,pattern=^https:\/\/app\.bilibili\.com\/bilibili\.app\.(view\.v1\.View\/View|dynamic\.v2\.Dynamic\/DynAll)$,requires-body=1,max-size=0,binary-body-mode=1,script-path=https://raw.githubusercontent.com/app2smile/rules/master/js/bilibili-proto.js
# 哔哩哔哩观影页面去广告
bilibili_json = type=http-response,pattern=^https?:\/\/api\.(bilibili|biliapi)\.(com|net)\/pgc\/page\/cinema\/tab\?,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/ddgksf2013/Scripts/master/bilibili_json.js
# 哔哩哔哩应用开屏广告预加载
bilibili_json = type=http-response,pattern=^https:\/\/app\.bilibili\.com\/x\/v2\/splash\/list,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/ddgksf2013/Scripts/master/bilibili_json.js
# 哔哩哔哩去除统一设置的皮肤
bilibili_json = type=http-response,pattern=^https?:\/\/app\.bilibili\.com\/x\/resource\/show\/skin\?,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/ddgksf2013/Scripts/master/bilibili_json.js
# 哔哩哔哩 1080P 高码率 + 4K (番剧和影视除外)
bilibili_json = type=http-response,pattern=^https?:\/\/app\.bilibili\.com\/x\/v2\/account\/myinfo\?,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/ddgksf2013/Scripts/master/bilibili_json.js
# 哔哩哔哩热搜发现
bilibili_json = type=http-response,pattern=^https://app.bilibili.com/x/v2/search/square,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/ddgksf2013/Scripts/master/bilibili_json.js
# 哔哩哔哩推荐去广告
bilibili_json = type=http-response,pattern=^https?:\/\/app\.bilibili\.com\/x\/v2\/feed\/index,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/ddgksf2013/Scripts/master/bilibili_json.js
# 哔哩哔哩追番去广告
bilibili_json = type=http-response,pattern=^https?:\/\/api\.(bilibili|biliapi)\.(com|net)\/pgc\/page\/bangumi,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/ddgksf2013/Scripts/master/bilibili_json.js
# 哔哩哔哩直播去广告
bilibili_json = type=http-response,pattern=^https?:\/\/api\.live\.bilibili\.com\/xlive\/app-room\/v1\/index\/getInfoByRoom,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/ddgksf2013/Scripts/master/bilibili_json.js
# 哔哩哔哩标签页处理
bilibili_json = type=http-response,pattern=^https?:\/\/app\.bilibili\.com\/x\/resource\/show\/tab,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/ddgksf2013/Scripts/master/bilibili_json.js
# 哔哩哔哩我的页面处理
bilibili_json = type=http-response,pattern=^https?:\/\/app\.bilibili\.com\/x\/v2\/account\/mine,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/ddgksf2013/Scripts/master/bilibili_json.js
# Adobe LightRoom 解锁 by deezertidal
http-response ^https:\/\/photos\.adobe\.io\/v2\/accounts* requires-body=1,script-path=https://raw.githubusercontent.com/litieyin/AD_VIP/main/Script/lightroom.js
# PhotoshopExpress 高级订阅 by deezertidal
http-response ^https:\/\/lcs-mobile-cops\.adobe\.io\/mobile_profile requires-body=1,script-path=https://raw.githubusercontent.com/litieyin/AD_VIP/main/Script/photoshop.js
# 解锁百度文档阅读权限 by deezertidal
http-response ^https:\/\/appwk\.baidu\.com\/naapi\/user\/getinfo requires-body=1,script-path=https://github.com/deezertidal/private/raw/master/js-backup/Crack/baidulibrary.js
[MITM]
hostname = %APPEND% appconf.mail.163.com,analytics.163.com,api.weibo.cn,mapi.weibo.com,*.uve.weibo.com,mbd.baidu.com,pan.baidu.com,m.ads.8le8le.com,iadmusicmat.music.com,ma-adx.ctrip.com,m.ctrip.com,api.m.jd.com,mp.weixin.qq.com,ocean.shuqireader.com,mi.gdt.qq.com,mobads.baidu.com,sq.sljkj.com,img-tailor.11222.cn,j-image.missfresh.cn,act.vip.iqiyi.com, gw.alicdn.com, heic.alicdn.com,apiwz.midukanshu.com,*.iqiyipic.com,*.iqiyi.com,*.adguard.org,photos.adobe.io,lcs-mobile-cops.adobe.io,appwk.baidu.com
